name: epipolar
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2024.3.11
  - certifi=2022.12.7
  - fftw=3.3.9
  - h5py=3.7.0
  - hdf5=1.10.6
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - numpy-base=1.21.5
  - openssl=1.1.1w
  - python=3.7.16
  - readline=8.2
  - scipy=1.7.3
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.38.4
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - cycler==0.11.0
      - easydict==1.13
      - fonttools==4.38.0
      - kiwisolver==1.4.5
      - matplotlib==3.5.3
      - numpy==1.21.6
      - opencv-python==4.9.0.80
      - packaging==24.0
      - pillow==9.5.0
      - pip==24.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - torch==1.10.0+cu111
      - torchaudio==0.10.0+rocm4.1
      - torchvision==0.11.0+cu111
      - typing-extensions==4.7.1
